server:
  port: 9005
  servlet:
    context-path: /sys
spring:
  datasource:
    primary: master #设置默认的数据源或者数据源组,默认值即为master
    strict: false
    dynamic:
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://10.66.106.5:3306/shpd_edu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: xieying
          password: xy%2Qmc99