server:
  port: 9005
  servlet:
    context-path: /sys
spring:
  redis:
    password: 3edc$rfv
  datasource:
    primary: master #设置默认的数据源或者数据源组,默认值即为master
    strict: false
    dynamic:
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://101.37.12.211:3309/shpd_edu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: xieying
          password: My4@8%feB
